### ISSUE TITLE
Documentation for `seval` plugin

### ISSUE THREAD

**Issue by graymalkin** [ellxc/piperbot#12]
`seval` is a powerful plugin which is quite complicated. It would be neat if there were a bit of documentation defining its features. It could be referenced in `#help seval` potentially.

**Comment by graymalkin** [comment]
I will get around to this, I'm waiting for some of the rest of the API to become more stable so examples written stay correct.

**Comment by graymalkin** [comment]
I will get around to this, I'm waiting for some of the rest of the API to become more stable so examples written stay correct.

**Comment by ellxc** [comment]
pretty stable now, and what changes shouldn't affect seval

**Comment by graymalkin** [comment]
Okay, I'll begin looking into the best way to present this. Would you object to something which builds a read-the-docs type static website which could be hosted as a github pages thing? This could then be linked to from error output in seval.

```
15:39 < graymalkin> #> a +=1
15:39 < Marvin> Exception: AugAssign(target=Name(id='a', ctx=Store()), op=Add(), value=Num(n=1))
```

This could link to specific documentation on infix operators like +=. Etc. Lots of room for a sane way to display things. We can do python style syntax highlighting on commads too, if we drop the initial `#`

```python
nicks || 
    karma || 
    filter message.data[1] != 0 || 
    cat || 
    > {"d" : json.dumps(
                    sorted(
                      message.data,
                      key=lambda x: x[1],reverse=True)
                      )
        } || 
    burl "https://graymalk.in/ircstats/karma-graph.html?" || 
    shurl
```
