### ISSUE TITLE
persistence for seval

### ISSUE THREAD

**Issue by ellxc** [ellxc/piperbot#15]
thinking is to store the values in mongo where appropriate, and when the values can't be pickled to pickle the AST representation for expression, with the at the time values subbed in in place of the corresponding names. this would have to be done at time of definition,
as pickling and unpickling can be slow, might be worth having local versions in dicts, and writing to mongo as definitions are made, but only reading from mongo at startup.

**Comment by graymalkin** [comment]
Does the speed matter too much? You could have save and load only happen at startup and shutdown. Or periodically on a long timer (and asynchronously)

**Comment by ellxc** [comment]
Actually for lambdas value subbing is not necessary.  But storing them separately from the rest or in a certain way so they can be loaded properly and put in the lambda wrapper will be necessary
