### ISSUE TITLE
allow commands to specify if input should not be piped in to them

### ISSUE THREAD

**Issue by ellxc** [ellxc/piperbot#28]
this would mean you couldn't abuse reminders or other commands which would be prone to spam

**Comment by graymalkin** [comment]
Maybe it would be better if you just made it so there was a per-user limit on the number of reminders that can be set. (And have a mechanism for storing that sort of information easily)

**Comment by ellxc** [comment]
that would fix reminders, and would probably be a good idea regardless, but for other things such as adding actions to the fite list it would probably be a good idea to do this.
or making it only accept the first input would solve the issue as well, this would still allow you to do clever things
