### ISSUE TITLE
convince people that piperbot is the one true bot framework and that false idols should be abandoned.

### ISSUE THREAD

**Issue by ellxc** [ellxc/piperbot#37]
baaaa

**Comment by bunu** [comment]
But Cirno is the strongest

**Comment by bunu** [comment]
stop putting words in my mouth penglose.

**Comment by bunu** [comment]
stop putting words in my mouth and deleting my things penglose

**Comment by graymalkin** [comment]
PiperBot is love.
PiperBot is life.
:pray:
