### ISSUE TITLE
Admin levels

### ISSUE THREAD

**Issue by graymalkin** [ellxc/piperbot#39]
It would be nice if there were a couple of levels of admin.

For example, having an administrator who may use `#load` `#unload` `#join` `#leave` etc, but not `#eval`.

My reasoning being you then have someone who can prevent the bot running a-muck; without giving them direct shell access to your machine via `#eval`

**Comment by ellxc** [comment]
changing it from a True/False on whether a person has admin or not to a privilege value should be sufficient, this would allow plugins to check yo privilege and restrict functionality based on the value returned.

**Comment by graymalkin** [comment]
I think there are some behaviours which could be "trusted" e.g. loading modules

**Comment by ellxc** [comment]
looking further into this it is going to have to tie in to #6 and #5
which will require quite a lot of work, and decent sized rewrite of the main bot to do it properly.

**Comment by graymalkin** [comment]
Perhaps you could provide an internal user api - to keep things sane.
