### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by egelmex** [ellxc/piperbot#41]

**Comment by egelmex** [comment]
https://pip.readthedocs.org/en/1.1/requirements.html

**Comment by graymalkin** [comment]
The pre-requisites are in the [readme](https://github.com/ellxc/piperbot/blob/master/README.md)

**Comment by egelmex** [comment]
pip freeze > requirements.txt if you use vertenv.

**Comment by graymalkin** [comment]
Don't be daft! ;)

**Comment by graymalkin** [comment]
I think it might be worth putting this on the backburner until the bot is more stable. @ellxc keeps making very large sudden changes to a lot of things at once (rightly, various things need changing), and some of the requirements are specific to plugins, etc. So some design decisions will need to be made.

In the mean time, the pre-requisites will get anyone up and running quite quickly.
