### ISSUE TITLE
Retrieving titles can result in mojibake

### ISSUE THREAD

**Issue by graymalkin** [ellxc/piperbot#42]
Presumably something somewhere isn't dealing with encoding properly.

I'd guess that a simple fix for this would be:

```python
title = brokenhtml.xpath("//title/text()").encoding("utf-8")
```

**Comment by ellxc** [comment]
this is could be a problem stemming from either requests or lxml, further testing is needed to work out where the problem comes from.

**Comment by ellxc** [comment]
now fixed
