### ISSUE TITLE
Is the mongo integration too deep?

### ISSUE THREAD

**Issue by graymalkin** [ellxc/piperbot#50]
Should Marvin be able to function without mongo? Currently the integration is very deep - perhaps it should be moved out to the plugin level a bit more cleanly.

On the same note maybe a plugin dependency system would be a good idea?

**Comment by ellxc** [comment]
allowing plugins to send data to the bot that it would then store would be a start, and then moving this functionality into a separate module which could then be replaced with a different database if desired. or allowing a fallback to JSON or xml if mongo or another database is not found.

**Comment by ellxc** [comment]
for now plugins that used mongo now save to their own json files in the main directory. only the markov plugin still uses mongo, but that is in no way core to the bot
