### ISSUE TITLE
Document `lxml` installation on Windows

### ISSUE THREAD

**Issue by graymalkin** [ellxc/piperbot#52]
Windows people will need a compiler on their `%PATH%` to build `lxml`. This is somewhat involved, so it would be nice to have a full set of instructions on this.

It will probably involve installing Visual Studio Express, as the default pip installation complains with this message:

```
error: Unable to find vcvarsall.bat
```

`vcvarsall.bat` puts various MSVC settings in the environment - and it's the 1st part of a Visual Studio C build chain.

**Comment by ellxc** [comment]
A work around would be to use the built-in XML and html parsing modules in python. while not quite as nice to use; it would remove this issue as well as reducing the number of dependencies.

**Comment by graymalkin** [comment]
I did some research, and it's not too hard to sort this. I have a local commit which will fix this issue. :)
