### ISSUE TITLE
Seval: Missing loops

### ISSUE THREAD

**Issue by graymalkin** [ellxc/piperbot#75]
```python
while condition: list(); of(); actions(); end. 
for x in range(y): list(x); of(); actions(); end.
```

**Comment by ellxc** [comment]
They would have to be implemented as functions, as they are invalid syntax as far as the AST is concerned. also the predicate/binding and the body would have to be strings, so that they can be evaluated multiple times. 
something like:
```python
x = 0; while("x <= 6", "x+=1; x")   => [1,2,3,4,5,6]
for("x", "range(5)", "x*x")   => [0,1,4,9,16]
```

**Comment by graymalkin** [comment]
Eww, that looks kinda gross. I don't know how the AST works underneath -- but if this is indeed the case it's very unsatisfying.

**Comment by ellxc** [comment]
the mode that I parse for seval in with the AST does not allow loops, so this would be the only way, also the words "while" and "for" are keywords, so it would also have to use "while_" and "for_" or something instead.

**Comment by graymalkin** [comment]
Could the be passed to a sub-AST?

On 15 Apr 2015 2:00 pm, ellxc <notifications@github.com> wrote:

the mode that I parse for seval in with the AST does not allow loops, so this would be the only way, also the words "while" and "for" are keywords, so it would also have to use "while_" and "for_" or something instead.

**Comment by ellxc** [comment]
I think this is beyond the scope of seval, and most features of a while and a for loop can be emulated in other ways, using list comprehensions and such
