### ISSUE TITLE
seval incorrectly calculates 0**0 as 1 instead of undefined

### ISSUE THREAD

**Issue by bunu** [ellxc/piperbot#89]

**Comment by graymalkin** [comment]
There's debate about this in the mathematical community, but it's fairly widely agreed that it should be 1. It is undefined, but it's neatest to just wave hands here and say it's `1`. 

http://mathforum.org/dr.math/faq/faq.0.to.0.power.html

http://www.askamathematician.com/2010/12/q-what-does-00-zero-raised-to-the-zeroth-power-equal-why-do-mathematicians-and-high-school-teachers-disagree/

https://www.math.hmc.edu/funfacts/ffiles/10005.3-5.shtml
